### ISSUE TITLE
[BUG] - unable to incorporate various .bs files in generateDocs task

### ISSUE THREAD

**Issue by mprather** [opencaesar/oml-tools#23] opened 2021-07-22 21:12 UTC
## Description
When calling bikeshed manually via the created publish.bat file from the intended target location (i.e. in the folder where the bad command from #22 intended the script to run), the firesat documentation runs in a variety of failures.

## Steps to Reproduce
- [ ] run ".\gradlew generateDocs". this will create a .bat file in the publish\bikeshed folder
- [ ] cd to publish\bikeshed
- [ ] run ".\publish.bat"

Result:
A variety of files report:
C:\src\firesat\build\bikeshed>bikeshed --die-on=link-error spec imce.jpl.nasa.gov/discipline/fse/assemblies.bs
LINE 10: Incorrectly formatted metadata line:
This software may be subject to U.S. export control laws. By accepting this software, the user agrees to comply with all applicable U.S. export laws and regulations. User has the responsibility to obtain export licenses,a or other export authority as may be required before exporting such information to foreign countries or providing access to foreign persons.

 ✘  Did not generate, due to fatal errors

## Expected Behavior
Documentation to be created w/o errors.

## Relevant screenshots
If applicable, add screenshots to help illustrate the issue.

**Comment by paulgaspardo** [comment] 2021-07-23 21:30
Looks like the problem is that the copyright all has to be on a single line, but on Windows it's appearing in 2 lines. The bug might be here where we remove newlines when we extract the copyright string from the OML vocabulary (which does contain a linebreak); on Windows line endings are generally `\r\n` but we are only matching on `\n`:

https://github.com/opencaesar/oml-tools/blob/master/oml-bikeshed/src/main/java/io/opencaesar/oml/bikeshed/OmlUtils.java#L81

I'll try replacing it with `\R` which should match any Unicode linebreak sequence

**Comment by melaasar** [comment] 2021-07-25 19:26
This was addressed in the v0.9.4 release

**Closed as completed by melaasar** 2021-07-25 19:26 UTC
Labels: Bug
